import Head from "next/head";
import Background from "../components/MyProjects";
import Header from "../components/Header";
import Hero from "../components/Hero";
import MyProjects from "../components/MyProjects";

export default function Home() {
  return (
    <div className="bg-body font-poppins text-white h-screen overflow-scroll z-0">
      <Head>
        <title>Gael Wumba Buatu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <section id="hero" >
        <Hero />
      </section>

      <section id="myProjects" className="h-screen">
        <MyProjects />
      </section>
    </div>
  );
}
