import { url } from "inspector";
import Head from "next/head";
import About from "./components/About";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Skills from "./components/Skills";
import Puissance4Mycinema from "./components/projets/Puissance4Mycinema";
import SortingEvalexpr from "./components/projets/SortingEvalexpr";
import SpotifyMyirc from "./components/projets/SpotifyMyirc";
import WysiwygMaquette from "./components/projets/WysiwygMaquette";

export default function Home() {
  return (
    <div className="bg-[#000000] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Gael Wumba Buatu</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero */}
      <section id="hero" className="snap-start">
        <Hero />
        {/* <NextButton /> */}
      </section>

      {/* About */}
      <section id="about" className="snap-center">
        <About />
      </section>

      {/* Skills */}
      {/* <section id="SpotifyMyirc" className="snap-center">
        <SpotifyMyirc />
      </section>

      <section id="Puissance4Mycinema" className="snap-center">
        <Puissance4Mycinema />
      </section> */}

      {/* <section id="WysiwygMaquette" className="snap-center">
        <WysiwygMaquette />
      </section> */}

      <section id="SortingEvalexpr" className="snap-center">
        <SortingEvalexpr />
      </section>

      {/* Projects */}

      {/* Contact me */}
    </div>
  );
}
